name: chafa # you probably want to 'snapcraft register <name>'
adopt-info: chafa
base: core18 # the base snap is the execution environment for this snap
#version: 'test' # just for humans, typically '1.2+git' or '1.3.2'
summary: CLI converter of image and GIFs to sizel or ANSI/Unicode characters # 79 char long summary
description: |
  Chafa is a highly configurable command line utility that converts images
  and GIFs into sixel or ANSI/Unicore character outputs. It has support 
  for alpha transparency, multiple colour modes and colour spaces, 
  combining selectable ranges of Unicode characters to product the desired
  output.

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el
  - build-on: armhf

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
  chafa:
    command: bin/chafa
    plugs: 
      - network
parts:
  chafa:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/hpjansson/chafa.git
    build-packages: [automake, libtool, libglib2.0-dev, libmagickwand-dev, gtk-doc-tools, docbook-xml, libxml2-utils]
    stage-packages: [imagemagick]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed -e 's/^v//')"

